 package com.tweetapp.entities;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.tweetapp.dto.Reply;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "tweet")
public class TweetsEntity {
	
	private String id;
	
	private String tweet;
	
	private String userTweetId;

	private Long tweetId;
	
	private Long like;

	private List<Reply> reply;
	
	private Date dateOfPost;

	@DynamoDBHashKey(attributeName ="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName ="tweet")
	public String getTweet() {
		return tweet;
	}
	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	@DynamoDBAttribute(attributeName ="userTweetId")
	public String getUserTweetId() {
		return userTweetId;
	}
	public void setUserTweetId(String userTweetId) {
		this.userTweetId = userTweetId;
	}

	@DynamoDBAttribute(attributeName ="tweetId")
	public Long getTweetId() {
		return tweetId;
	}
	public void setTweetId(Long tweetId) {
		this.tweetId = tweetId;
	}

	@DynamoDBAttribute(attributeName ="like")
	public Long getLike() {
		return like;
	}
	public void setLike(Long like) {
		this.like = like;
	}

	@DynamoDBAttribute(attributeName ="reply")
	public List<Reply> getReply() {
		return reply;
	}
	public void setReply(List<Reply> reply) {
		this.reply = reply;
	}

	@DynamoDBAttribute(attributeName ="dateOfPost")
	public Date getDateOfPost() {
		return dateOfPost;
	}
	public void setDateOfPost(Date dateOfPost) {
		this.dateOfPost = dateOfPost;
	}

}